### ISSUE TITLE
OSA Series 2 Meeting Jan 14th

### ISSUE THREAD

**Issue by danaklug** [opensourceantibiotics/Series-2-Diarylimidazoles#108]
_This page is draft until this text is removed._

Meeting Jan 14th 2021 at 2pm UK time at https://ucl.zoom.us/j/92800004715. Follows on from #106   

Recording: 

On the call: 

**PREVIOUS ACTIONS**

- [ ] [Samples](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/105#issuecomment-992671988) from @QSimpson and @edwintse to be tested ASAP. @edwintse to organise date for this with Paul.
- [ ] Awaiting ADME data on compounds in #104 
- [ ] Have we had these compounds evaluated in a kinase panel screen?
- [ ] Everyone is encouraged to look at the draft paper posted by @danaklug and contribute/comment #101 
- [ ] Anyone used/want to use the Discussions function, above?
- [ ] @mattodd to post latest meeting(s) to Youtube - slight backlog.
- [x] @danaklug will assemble the Christmas Open Source Antibiotics newsletter, which will have 3 science updates from this series as well as three from the mur ligase project. Keep an eye out for this - the newsletter needs to be short and sweet and understandable by someone who is not closely following the project detail.

**Comment by danaklug** [comment]
I've had a few updates by email from Alex as she is still on holiday until next week.

- The DNA sequences she ordered were delivered to UCL so she'll get onto the binding assay as soon as she is back. 
- She's progressing completion of her table and @edwintse and I have been in touch with her about supplying additional compounds, including the resynthesized 983.
- She will also begin adding her data to the paper draft when she returns.

**Comment by edwintse** [comment]
Screen of NEU compounds from @QSimpson to be done next Wednesday 19/1/22
