### ISSUE TITLE
OSA Series 2 Meeting Feb 11th (No meeting Feb 4th)

### ISSUE THREAD

**Issue by edwintse** [opensourceantibiotics/Series-2-Diarylimidazoles#110]
_This page is draft until this text is removed._

Meeting Jan 11th 2021 at **3pm** UK time at https://ucl.zoom.us/j/92800004715. Follows on from #108

Recording: 

On the call: 

**PREVIOUS ACTIONS**

- [ ] Discussion of new potency data in #109
- [ ] Alex to update on tox and DNA binding experiments
- [ ] Awaiting ADME data on compounds in #104 
- [ ] Updates as to @mattodd's correspondence with Lee Graves (#106)?
- [ ] Have we had these compounds evaluated in a kinase panel screen?
- [ ] Everyone is encouraged to look at the draft paper posted by @danaklug and contribute/comment #101 
- [ ] Anyone used/want to use the Discussions function, above?
- [ ] @mattodd to post latest meeting(s) to Youtube - slight backlog.
