### ISSUE TITLE
OSA Series 2 Meeting Apr 6th

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#114]
_This post is draft till this text is removed_

Meeting April 6th at **4pm** UK time at https://ucl.zoom.us/j/92800004715. Follows on from #113

Recording: 

On the call: 

**PREVIOUS ACTIONS**

- [ ] Alex to update on final tox measurements and upload data from DNA binding experiments that were described in #113 
- [ ] Have we had these compounds evaluated in a kinase panel screen?
- [ ] Everyone to look at the draft paper posted by @danaklug and contribute/comment #101 

**Today**:
- [ ] Lee Graves to present latest MoA data (#106)?
- [ ] @danielgedder to update on latest synthesis, i.e. update on #112 

**Mothballed**:

- [ ] Anyone used/want to use the Discussions function, above?
- [ ] @mattodd to post several older meeting(s) to Youtube - slight backlog?

**Comment by danielgedder** [comment]
Hello everyone, update done at #112. I will talk more about the new analogs during the meeting.

**Comment by danielgedder** [comment]
**Actions**

- [ ] ACTION ITEM: Set a date for the next MRSA biological assay (maybe April 22nd) for @danielgedder and Maria's compounds;

- [ ] ACTION ITEM: @MFernflower check with DNDi the availability to test the new set of compounds against T. Cruzi, T.brucei, Leishmania, and mammalian cytotoxicity 

- [ ] ACTION ITEM:  @danielgedder searches the targets mentioned by Lee and checks information about potential inhibitors and research groups working with these targets;

**Comment by MFernflower** [comment]
If I'm not mistaken @lferrins has the direct DNDI contact

**Comment by lferrins** [comment]
@MFernflower you are right, thanks ;) 

Yes, if you would like to ship more compounds to DNDi I can certainly help get that done!

**Comment by danielgedder** [comment]
Sorry @MFernflower, I tagged you by mistake. @lferrins I would like to test the 8 diarylimidazoles derivatives that I am working on here, plus 10 indazol derivatives synthesized in Brazil. All the 18 compounds will be tested against MRSA and I would like to send them to DNDi as well. I have a collaboration with professor Maes and Guy from Antwerp. I don't know which lab you usually send the samples to, but  if you are going to send them to the University of Antwerp (Laboratory of Microbiology, Parasitology and Hygiene), I can contact professor Maes and Guy, in case you prefer. Please, let me know! Thank you!

**Comment by danielgedder** [comment]
**REPORT**
Hello everyone, I have made some researchers based on Lee’s presentation and some of the target that he spoken about. 
The starting point was a screening of GlaxoSmithKline internal library collection for inhibitors of the transforming growth factor β1 (TGF- β1) type I receptor (ALK5), it was identified 2-Diarylimidazoles as a promising hit (compound 7 IC50 of 0.46 µM against ALK5 and non-inhibition against p38 kinase). ALK5 is the receptor of TGF-β and plays a pivotal role in the canonical TGF-β signaling pathway. The inhibitor 7 inhibits TGF- β1- induced fibronectin (FN) mRNA (IC50 of 0.50 µM) in A498 cells. Further optimizations lead to selective inhibitor 14 (IC50 of 0.094 µM against ALK5 and non inhibition against p38 kinase, LD50 > 30 uM), which inhibits TGF-β[1](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/114#_ENREF_1)-induced fibronectin mRNA (IC50 of 0.05 µM) formation while displaying no measurable cytotoxicity in the 48 h XTT assay. ¹
![image](https://user-images.githubusercontent.com/88835924/164736558-e0918571-2a61-4707-bd36-77b92ee54fc0.png)

 
The second publication was in 2009, the authors described that the compound OSA_812 is TGFR1 inhibitor. 
![image](https://user-images.githubusercontent.com/88835924/164736676-c96c03ae-afdd-4f95-a32b-1f4fb62d5548.png)


 
[http://www.bindingdb.org/bind/chemsearch/marvin/MolStructure.jsp?monomerid=50110206](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.bindingdb.org%2Fbind%2Fchemsearch%2Fmarvin%2FMolStructure.jsp%3Fmonomerid%3D50110206&data=04%7C01%7Cmatthew.todd%40ucl.ac.uk%7Cab2eef864d014eb2dceb08da195b554e%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637850177299182651%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mEisYY4t6%2BM69BGOie2Mze%2FfwBRCugdUSxolW5NkMis%3D&reserved=0)


Analogue DGS245 is known selective inhibitor of ALK5:
![image](https://user-images.githubusercontent.com/88835924/164736719-70ff193a-e36a-4220-af10-e01ef96bad0e.png)

 
I have done a search at ChEMBL database to filter only compounds selectively potent against NEK2, NEK3, CSNK1E and TGFRB1with the available bioactivities. The database containing about 9 thousand molecules with available bioactivities were extracted (NEK2 – 3324 compounds; NEK3 – 817 compounds; CSNK1E – 1207; TGFRB1 – 3536). I have attached the file. 



After applying appropriated filters, I have found 103 compounds containing 5,6-dihydro-4H-pyrrolo[1,2-b]pyrazole, similar to OSA compounds. These pyrrolo[1,2-b]pyrazole derivatives  showed activity against TGF-beta receptor type 1. For example compounds DGS_5727 and 4636.
![image](https://user-images.githubusercontent.com/88835924/164737004-53077c82-b781-4355-a304-75100d0134f4.png)
![image](https://user-images.githubusercontent.com/88835924/164737025-6ef441d0-febf-4a3c-b300-f2a7217386ad.png)

 
 
One pyrrolo[1,2-b]pyrazole derivative was also tested against Serine/threonine-protein kinase NEK2, but it was inactive. 

 
![image](https://user-images.githubusercontent.com/88835924/164737057-31eef844-370f-4780-bd52-4f75524fa1be.png)


	5,5-dimethyl-5,6-dihydro-4H-pyrrolo[1,2-b]pyrazole kinase assays reveal high activity towards ALK5. Mechanism of action in cells corresponds to ALK5 inhibition. Compounds display low cytotoxicity in cell lines. [2](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/114#_ENREF_2)


Many other examples have the pyridine attached to the core ring and it resulted in activity against TGF-beta receptor type I in different assays. See the compounds below:
 
 
![image](https://user-images.githubusercontent.com/88835924/164737106-bb5fa285-34c6-45bd-b996-28173c6f8d46.png)
![image](https://user-images.githubusercontent.com/88835924/164737131-7e8a06a4-a06c-443c-ae1c-d7f4c564a900.png)
![image](https://user-images.githubusercontent.com/88835924/164737151-7d8a0f22-2455-4d9f-a14d-6d3eb062fdc8.png)
![image](https://user-images.githubusercontent.com/88835924/164737174-9fb342fd-36b5-4767-8295-4ed09ebed468.png)

 
 

Other compounds did not have the pyridine moiety but it showed high activity against TGF-beta receptor type I:

 
![image](https://user-images.githubusercontent.com/88835924/164737203-afaae724-4ec2-4a36-81e8-477e768359fd.png)
![image](https://user-images.githubusercontent.com/88835924/164737225-f326128f-0d9d-49d9-a51f-d4c1a10637f9.png)

 

	Pyrrolo[1,2-a]imidazole derivatives were tested against Serine/threonine-protein kinase (NEK2), but no activity was detected. 
 
![image](https://user-images.githubusercontent.com/88835924/164737281-79b116d8-d25e-4889-90d3-34a00ad39ffe.png)
![image](https://user-images.githubusercontent.com/88835924/164737297-ed7e087c-4ad9-4f8e-b0b1-ae197c29d5e3.png)

 
A set of 109 Pyrrolo[1,2-a]pyrazine derivatives were tested against CSNK1E and it showed to be a promising inhibitor. Eight compounds showed IC50 of 1 nM.

![image](https://user-images.githubusercontent.com/88835924/164737399-f2236218-def8-465c-8544-afc77af5b5be.png)
![image](https://user-images.githubusercontent.com/88835924/164737418-d9748526-6e5a-444d-a699-bab5ad74461d.png)

 
 

 

1.	Callahan, J. F.; Burgess, J. L.; Fornwald, J. A.; Gaster, L. M.; Harling, J. D.; Harrington, F. P.; Heer, J.; Kwon, C.; Lehr, R.; Mathur, A.; Olson, B. A.; Weinstock, J.; Laping, N. J., Identification of novel inhibitors of the transforming growth factor beta1 (TGF-beta1) type 1 receptor (ALK5). J Med Chem 2002, 45 (5), 999-1001.
2.	Řezníčková, E.; Tenora, L.; Pospíšilová, P.; Galeta, J.; Jorda, R.; Berka, K.; Majer, P.; Potáček, M.; Kryštof, V., ALK5 kinase inhibitory activity and synthesis of 2,3,4-substituted 5,5-dimethyl-5,6-dihydro-4H-pyrrolo[1,2-b]pyrazoles. European Journal of Medicinal Chemistry 2017, 127, 632-642.

**Comment by danielgedder** [comment]
Hi everyone! I have done research on potential collaborators for enzyme assays; so far, I have found this list below. I sent an e-mail to Tania asking her if she could assay the compounds. She works in FioCruz in Brazil. She has published papers with Sabine from France with ALK5 assays. Maybe I can send an e-mail to Sabine as well.  

ALK5 TGF-B assays  

Tania C. Araujo-Jorge - Brazil 

taniaaj@ioc.fiocruz.br <[taniaaj@ioc.fiocruz.br](mailto:taniaaj@ioc.fiocruz.br)>; 

 

[Sabine Bailly](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fjournals.asm.org%2Fdoi%2F10.1128%2FAAC.00022-07%23con9&data=05%7C01%7Cmatthew.todd%40ucl.ac.uk%7Cbaaf9daefe804b0dc30e08da3f06b161%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637891595211789866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=gNntskefQUb6HP8xU8VYIjLdzK7bR%2Fydnz4fZ3%2FOlnQ%3D&reserved=0) - France 

[sbailly@cea.fr](mailto:sbailly@cea.fr) <[sbailly@cea.fr](mailto:sbailly@cea.fr)>; 

 

There is a group in UCN that runs biological assays for all the targets we are interested in assay our compounds. 

Group in UNC 

[https://pharmacy.unc.edu/research/centers/sgc-unc/resources/](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpharmacy.unc.edu%2Fresearch%2Fcenters%2Fsgc-unc%2Fresources%2F&data=05%7C01%7Cmatthew.todd%40ucl.ac.uk%7Cbaaf9daefe804b0dc30e08da3f06b161%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637891595211789866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=Ap1o%2FoqcALmcpAOtWTxCsrBFw%2FkCe9tiVHeDLAqjVjM%3D&reserved=0) 

 

NEK2/3 

Department of Pharmaceutical Sciences, College of Pharmacy, University of Arkansas for Medical Sciences, Little Rock, AR, USA 

[Hong-yuLia](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.sciencedirect.com%2Fscience%2Farticle%2Fpii%2FS0223523420306632%3Fvia%253Dihub%23!&data=05%7C01%7Cmatthew.todd%40ucl.ac.uk%7Cbaaf9daefe804b0dc30e08da3f06b161%7C1faf88fea9984c5b93c9210a11d9a5c2%7C0%7C0%7C637891595211789866%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=OtKQ1PrnbjCC4SbRTVhCqapOj8rI0B30qKn0HVOhnFI%3D&reserved=0) 

[HLi2@uams.edu](mailto:HLi2@uams.edu)
