### ISSUE TITLE
OSA Series 2 Meeting June 10th

### ISSUE THREAD

**Issue by mattodd** [opensourceantibiotics/Series-2-Diarylimidazoles#115]
_This post is draft till this text is removed_

Meeting June 10th at 2pm UK time at https://ucl.zoom.us/j/92800004715. Follows on from #114

Recording: 

On the call: 

HI @opensourceantibiotics/series-2-diarylimidazoles - time to finish up the tox, DNA binding, MoA experiments and to advance the paper writing towards a submission.

**Active Priorities for Discussion**

- [ ] Consider [latest potency data](https://github.com/opensourceantibiotics/Series-2-Diarylimidazoles/issues/112#issuecomment-1122159973) including re-test of compounds that is taking place June 7th/8th.
- [ ] Alex to update on final tox measurements and upload data from DNA binding experiments that were described in #113 
- [ ] Everyone to look at the draft paper posted by @danaklug and contribute/comment #101 
- [ ] Lee Graves and team to upload previously-presented MoA data and to update on MRSA experiment
- [ ] Consider the targets suggested by Lee's data, including the question of whether the compounds have been evaluated in a kinase panel screen.
- [ ] Consider any remaining synthetic targets for this paper.
- [ ] Update on which other compounds are being evaluated vs other pathogens (and any expected incoming tox data).

**Mothballed**:

- [ ] @mattodd to post several older meeting(s) to Youtube - there is a slight backlog.

**Comment by danielgedder** [comment]
Hi everyone, we re-tested some OSA_975 derivatives against MRSA and MSSA and we got the same results. OSA001052 was 16mcg/mL against both strains. OSA001053, OSA001072-OSA001077 was >32 mcg/mL against both strains. OSA000821 and OSA000822, showed MIC values of 4 mcg/mL against both strains (MSSA and MRSA). Vancomycin MIC was 1 mcg/mL for both strains.

![osa_meeting10-06-22](https://user-images.githubusercontent.com/88835924/173066137-d8d4eee3-728c-411e-ba91-c4204b66b11e.gif)

**Comment by mariadichiara** [comment]
Hi @danielgedder, this is a summary of NEU synthesis/purification
 
![image](https://user-images.githubusercontent.com/99894833/173410441-2fa570df-f5cc-4faf-a50a-d054d0f4fcf0.png)

We decided to cancel the following molecule since the alkylation of the intermediate has occurred at the undersired _N_-position

![image](https://user-images.githubusercontent.com/99894833/173410890-3b3ab07b-b5e2-44e0-999d-8c391d225bfd.png)

**Comment by mattodd** [comment]
Welcome aboard @mariadichiara

**Comment by mariadichiara** [comment]
Thanks @danielgedder! These are the conditions I used 

![image](https://user-images.githubusercontent.com/99894833/173710762-c269083b-3b72-4c55-a437-fa0f43f8477f.png)

In all three conditions I was not able to see any tiny signal of my final compound. I m trying with protected imidazole now, maybe this is the problem. I could try your conditions too

**Comment by danielgedder** [comment]
@mariadichiara, I guess you using the protected imidazole is a great strategy.

**Comment by MFernflower** [comment]
@mariadichiara maybe try johnphos?
